### PR TITLE
Fix issues with cassette playback during VirtFS activation.

### PR DESCRIPTION
**Pull request by roliveri**

### CODE REVIEW

**Comment by movitto** [comment]
@roliveri hey rich, having some trouble w/ the specs before applying this PR so will need to sort those out before I can verify.

But overall this just adds the 'CcReal' classes so as to distinguish their recording in the camcorder cassette files correct? And the specs are just the existing specs applied to this new context?

It does seem a little round-about to introduce this new inheritance level just for this one edge case but if it works for now it's fine until we figure something better out.

**Comment by roliveri** [comment]
@movitto I didn't have any trouble running the specs on my MAC. Maybe I should try running them on a Linux VM.

Yep, I duplicated the File and Dir instance specs and ran them with VirtFS activated.

I don't see any other way to accomplish what we need. We need a reference that reports the class name of something that will always point to the original File class. This seems to be the simplest and most lightweight way of accomplishing that.

**Comment by movitto** [comment]
Hey rich, just tested this out w/ the example scripts we were trying last week and it worked, the correct class hierarchy was captured / replayed. I also tested the specs (with my fixes applied, see pr #7 ) and everything looks good.

As far as mitigating the newly added heirarchy I was thinking if we could figure out a way to defer the mapping on the native ruby classes to their virtfs correspondencies until after the activation process is fully complete then we might be able to avoid this whole issue. That being said, since as you say this works for now, and there is plenty of other stuff tbd, I'd be fine w/ merging this as is. +1

**Comment by movitto** [comment]
@roliveri ^

**Comment by roliveri** [comment]
@movitto We can't defer the mapping of the native ruby classes to their virtfs counterparts until after the activation process is fully complete, because that mapping defines the activated state - if the classes aren't mapped, we're not activated.

CamcorderFS doesn't, and shouldn't, know anything about the current activation state. All it needs is are classes that will always represent the native classes, and will always return the same class.name.
It seems any other solution would be more complex, and not buy us anything.

Remember, we're only adding to the class hierarchy, we're not adding another level of indirection, so it should have no impact on performance.

**Pull request merged**
